apiVersion: v1
kind: Secret
metadata:
  name: mysql
data:
  ### need to convert to encrypted format "  echo -n 'value' | bash64  " ---> provides the encoded format ####
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  WORDPRESS_DB_PASSWORD: cGFzc3dvcmQ=