apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  ### need to convert to encrypted format "  echo -n 'value' | bash64  " ---> provides the encoded format ####
  MYSQL_DB_HOST: mysql
  MYSQL_ROOT_PASSWORD: password