apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
spec:
  accessModes:
##################### ReadWriteOnce,ReadOnlyMany ##############
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi