apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
data:
  ### need to convert to encrypted format "  echo -n 'value' | bash64  " ---> provides the encoded format ####
  WORDPRESS_DB_HOST: mysql:3306
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: password

