apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    apptype: frontend
  ports:
    - port: 80
      targetPort: 8080